name: pos_demo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0
environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.2.0
  dio: ^5.4.0
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  transparent_image: ^2.0.1
  intl: ^0.19.0
  flutter_screenutil: ^5.9.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1


flutter:
  uses-material-design: true

